### ISSUE TITLE
More settings page options

### ISSUE THREAD

**Issue by anthonyfabius** [EasyApp-RPI/EasyApp#8]
As of right now we only have Name, Major, Interests, and Supplementary text. Adding options for email, phone number, and address would be helpful. Also splitting name into first, middle, and last could be helpful.

**Comment by DavidASC20** [comment]
for autofilling job applications, would also need to add ethnicity, veteran status, if they have a disability or not

**Comment by Katijino** [comment]
Instead of simply allowing for supplementary text, allowing for people to Input previous places of employment and/or notable achievements (up to certain #) that weren't included in their resume. also age if it's not on there.

**Comment by anthonyfabius** [comment]
Closing this issue since we have a more formal request in #16 . Any new ideas can go to that issue.
