### ISSUE TITLE
Yaml for custom issues and prs

### ISSUE THREAD

**Issue by anthonyfabius** [EasyApp-RPI/EasyApp#9]
Add github pr and issue yamls to main branch for a nicer layout and guided questions.

**Comment by LeadFreeCandy** [comment]
This and I think we should also make a contributing.md for some style guidelines for adding code

**Comment by anthonyfabius** [comment]
> This and I think we should also make a contributing.md for some style guidelines for adding code

I saw this way too late. I'll add this in a little.

**Comment by anthonyfabius** [comment]
Just added a yaml for questions. After contributing.md is added i'm closing this issue.
